resources/ids.md
- the source takes up less space and with better readability
- unlikely to work outside Github's flavor of markdown
=> Update ids.md to Utilize GitHub’s Flavor of Markdown

resources/blue-stag-decompilation.md
=> Update blue-stag-decompilation.md to Fixed RetroMCP-Java Link

jar/README.md
For anybody who uses Linux, I got you :)
=> Add Linux guides

chat_messages/Version 06
all chat logs of the video "Version 06"
=> Version 06

chat_messages/Version 07
all chat logs of the video "Version 07"
=> Version 07

chat_messages/version-10
as always all the chat logs of the video "Version 10"
=> version-10

chat_messages/internal-footage-3
that was a painful documentation
=> internal-footage-3

chat_messages/presentation
ok we are getting there, two more videos to go
=> presentation

chat_messages/discovered
=> discovered

chat_messages/internal-footage-3.md
=> Fixed some grammatical mistakes

items/blue_flame.md
=> blue_flame.md

README.md, resources/github-messages.md, resources/preview-analyzation.md
I'm unsure if this is valuable or not, but still
=> Add GitHub replies by exalpha-dev

videos/version-06.md
=> Version-06: Anomalies

README.md
=> Add Rosepad

resources/blue-stag-decompilation.md
why do you need to use recaf? why do you need to exclusively use vscode? why is it such a mess????
=> clean up decomp instructions

README.md, lore/other-characters.md, videos/punishments.md
wake up babe, new Minecraft Alpha 1.0.16 Versions video dropped
=> Punishments Video

videos/consequences.md
added more details about vivivern and PISSMAN-PC as PISSMAN was recording the screen and the chat was with Viviern (can be seen on the chat window), not sure if the launcher can be fully be considered an anomaly but it needs to be cited for future reference
=> Update consequences.md as some details were omitted

videos/version-13.md
Apparently there's a detail of Version 13 that wasn't reported, this pr is to ammend such detail
=> Updated Version 13, pointing out an anomaly

README.md, chat_messages/consequences.md, lore/other-characters.md, videos/consequences.md, videos/version-13.md
* Removed chat logs from videos/consequences.md and put it in chat_messages
* Add Vivern
* Fixed some lore from Version 13
=> Just some small stuff

resources/preview-2-analyzation.md
it says the enter key enables cheats
=> FIX hte fucking text

resources/deobfuscation.md
not great, might add some  premade mappings or an already deobfuscated jar later
=> deobfuscation guide for unrpreview2

README.md, resources/deobfuscation.md
you can actually decompile now
=> more deobfuscation and decompilation shit

resources/deobfuscation.md
add obfuscated decompilation thing cause apparently it works? and server
=> not really organized that well but im bad at this

README.md
=> More community resources

videos/internal-footage-4.md
Appears 720p60 on YouTube - https://i.imgur.com/xm9FdHY.png
Appears 720p59.94 downloaded from YouTube - https://i.imgur.com/TQSiF6A.png
=> Fixed YouTube Link/FPS/Res on IF4

README.md, videos/reinsertion-point.md
=> Reinsertion point

README.md
Apparently i made a typo, this patch is to fix that
=> Patch 1.5/2? Fixed typo

README.md, videos/reinsertion-point.md
We do have something like a date for Version 06, based on the changelog and the video Consequences, retracted a possible mistake i made by watching Reinsertion Point as i might have went overhead with thinking who was talking with Pissman-PC and added context for how Sighting  6 is confirmed
=> Patch 3/2 Just small updates

videos/attachment_b849.avi.md
Added Information and specific timestamps.
=> Add attachment_b849.avi.md

README.md, videos/attachment_b849.avi.md
Sorry for 2nd pull request, i meant to merge this one and #89.
=> Added more attachment_b849.avi content

videos/attachment_b849.avi.md
Fixed what looked a dirty copy paste
=> Fixed title of the file

README.md, chat_messages/home.md, videos/home.md
would of been faster if i had notis on alphaver channel
=> AlphaVer Video Speedrun

videos/sunrise.md
I correctly guessed that Sunrise at Denmark.ogg plays during Sunrise, then figured out that it actually plays during the moon sequence, while Denmark.ogg plays at the start of the video. I don't know what is the track that plays during the nebula/dev2 sequence.
=> Naming two of Sunrise's three music tracks
